### ISSUE TITLE
Platform error image_processing.deepstack_object - Integration 'deepstack_object' not found.

### ISSUE THREAD

**Issue by mtweldon** [robmarkcole/HASS-Deepstack-object#109]
Have seen the FAQ, but I'm not running hassio or docker. 

Installed deepstack from HACS. 

Home Assistant 0.106.2 running in python venv. 

Deepstack running on a separate system. Curl works to show that deepstack is running just fine. 

```
image_processing:
  - platform: deepstack_object
    ip_address: 192.168.1.2xx
    port: 80
    # api_key: Mysecretkey
    # scan_interval: 30 # Optional, in seconds
    save_file_folder: /config/snapshots/
    save_timestamped_file: True
    target:
      - person
      - car
    source:
      - entity_id: camera.front
        name: deepstack_person_detector
```
