### ISSUE TITLE
Doesn't seem to be doing anything

### ISSUE THREAD

**Issue by mf-social** [robmarkcole/HASS-Deepstack-object#110]
I have installed the custom_component via HACS and put the deepstack docker container in Homessistant via the portainer addon (using the noavx image).

If I visit the IP address and port in a browser I get the DeepStack Activated screen with 729 days left on the subscription.

if I visit the logs for the docker container I can see my laptop's IP visiting that page:

```
[GIN] 2020/03/11 - 13:29:35 | 200 |     554.317µs |       10.0.0.86 | GET      /
[GIN] 2020/03/11 - 13:29:35 | 200 |    3.625199ms |       10.0.0.86 | GET      /assets/vendor/fontawesome-free/css/all.min.css
[GIN] 2020/03/11 - 13:29:35 | 200 |     245.349µs |       10.0.0.86 | GET      /assets/vendor/simple-line-icons/css/simple-line-icons.css
[GIN] 2020/03/11 - 13:29:35 | 200 |     225.032µs |       10.0.0.86 | GET      /assets/device-mockups/device-mockups.min.css
[GIN] 2020/03/11 - 13:29:35 | 200 |     166.634µs |       10.0.0.86 | GET      /assets/css/new-age.min.css
[GIN] 2020/03/11 - 13:29:35 | 200 |    7.415126ms |       10.0.0.86 | GET      /assets/vendor/bootstrap/css/bootstrap.min.css
[GIN] 2020/03/11 - 13:29:35 | 200 |     345.121µs |       10.0.0.86 | GET      /assets/img/deepstack.png
[GIN] 2020/03/11 - 13:29:35 | 200 |     282.597µs |       10.0.0.86 | GET      /assets/img/loader.gif
[GIN] 2020/03/11 - 13:29:35 | 200 |     371.705µs |       10.0.0.86 | GET      /assets/img/iot.jpg
[GIN] 2020/03/11 - 13:29:35 | 200 |     203.141µs |       10.0.0.86 | GET      /assets/img/dark-background.png
[GIN] 2020/03/11 - 13:29:35 | 200 |     333.177µs |       10.0.0.86 | GET      /assets/img/deepstack.png
```

The custom component appears to have installed correctly as I get the 'warning' that I am using a custom_component and the 'sensors' are created - 

```
image_processing:
  - platform: deepstack_object
    ip_address: 10.0.0.68
    port: 8950
    api_key: MY_KEY
    # scan_interval: 30 # Optional, in seconds
    save_file_folder: /config/camera/
    save_timestamped_file: True
    target:
      - person
      - car
    source:
      - entity_id: camera.front
        name: deepstack_front_test
  
  - platform: deepstack_object
    ip_address: 10.0.0.68
    port: 8950
    api_key: MY_KEY
    # scan_interval: 30 # Optional, in seconds
    save_file_folder: /config/camera/
    save_timestamped_file: True
    target:
      - person
      - car
    source:
      - entity_id: camera.drive
        name: deepstack_drive_test
```

(note, I'm using port 8950 as 5000 is in use, but it is correctly mapped in the docker config, as per being able to view the API screen in the browser)

So, I have the following:

image_processing.deepstack_drive_test | unknown | summary:  {}  unit_of_measurement:  friendly_name: deepstack_drive_test
-- | -- | --
image_processing.deepstack_front_test | unknown | summary:  {}  unit_of_measurement:  friendly_name: deepstack_front_tes

But they never change.

I have changed my logger level to debug and custom_components.deepstack_object doesn't appear at all.  Like it's not doing anything.  Searching for 'deepstack' just shows the image_processing sensors updating with everything else, obviously with no state changes.  The log for the docker container does not register any new connections.

Thoughts?
