### ISSUE TITLE
deepstack always targets car even if it's not in configuration?

### ISSUE THREAD

**Issue by pejotigrek** [robmarkcole/HASS-Deepstack-object#111]
I'm tinkering my config for a few days for now, and after testing phase I am now clearing the config from stuff that will be useless in my scenario.

this is my configuration yaml used for detection:

```
### camera image detection
image_processing:
  - platform: deepstack_object
    ip_address: !secret deepstack_ip
    port: 5000
    api_key: !secret deepstack_api
    scan_interval: 86400
    timeout: 60
    save_file_folder: !secret deepstack_folder
    save_timestamped_file: true
    target:
      - person
      - bicycle
      - dog
      - cat
    source:
      - entity_id: camera.3_out_driveway
        name: 3_out_driveway

### just a part of the configuration for sensor that prioritizes detected objects person>bicycle>dog>cat
sensor:
  - platform: template
    sensors:
      3_out_driveway_occupancy:
        entity_id:
        - binary_sensor.3_out_driveway_motion
        - image_processing.3_out_driveway
        value_template: >
          {% if is_state('binary_sensor.3_out_driveway_motion','off') %}
            off
          {% else %}
            {% set temp_json = state_attr('image_processing.3_out_driveway', 'summary') %}
            {% set temp_conf = {"person":8, "bicycle":4, "dog":2, "cat":1} %}
            {% set temp_stat = namespace(value=0) %}
            {% for temp in temp_json -%}{% if (temp_json[temp] > 0) %}{% set temp_stat.value = temp_stat.value + (temp_conf[temp]|int) %}{% endif %}{% endfor %}
            {% if (temp_stat.value >= 8) %}person
            {% elif (temp_stat.value >= 4) %}bike
            {% elif (temp_stat.value >= 2) %}dog
            {% elif (temp_stat.value == 1) %}cat
            {% else %}off{% endif %}
          {% endif %}

### my camera's motion detection sensor that triggers the automation to scan
binary_sensor:
  - platform: mqtt
    state_topic: "3_out_driveway/motion"
    name: 3_out_driveway_motion
    payload_on: "motion_start"
    payload_off: "motion_stop"
    device_class: motion

### and lastly - the automation
automation:
  - id: 3_out_driveway_motion
    alias: 3_out_driveway_motion
    trigger:
    - platform: state
      entity_id: binary_sensor.3_out_driveway_motion
      to: "on"
    action:
    - service: image_processing.scan
      entity_id: image_processing.3_out_driveway
```

I have a 24h scan interval, because I trigger scan only after my camera detects movement.
as you can see - my targets are people, bicycles and two types of animals. I've got few trees visible by the camera, so scan is triggered quite often. I do have a car in the field of vision too, that's why I don't want to detect this, as it probably almost always would be true.

after triggering the scan I have an error in the log:

```
2020-05-06 10:25:22 ERROR (MainThread) [homeassistant.components.template.sensor] Could not render template 3_out_driveway_occupancy: UndefinedError: 'dict object' has no attribute 'car'
```

and looking in the developer tools/states `image_processing.3_out_driveway` looks like this:

| image_processing.3_out_driveway | 0 | summary:  car: 1|
|----|----|----|

I've restarted everything - HA device, HA container, deepstack container. no change - it always finds car, even if it doesn't supposed to.
