### ISSUE TITLE
100% CPU - Possibly IR Camera image killing Deepstack detect API

### ISSUE THREAD

**Issue by jonwilliams84** [robmarkcole/HASS-Deepstack-object#114]
Running the GPU image...

Deepstack will sit there quite happily for hours detecting objects, then as soon as night time falls and my cameras switch to IR, after 1 or 2 scans the CPU will sit at 100% and the API becomes unresponsive until I restart the container.

Happy to provide additional logs / debugging info because currently I have had to add a healthcheck the stack in order to kill the container off when this happens, which is throughout the night… but this is less than ideal as the healthcheck itself is consuming CPU and GPU cycles.

The way I have achieved the healthcheck is by adding ‘curl’ to the image, bind mounting a directory with a sample image inside and then adding this to my docker-compose.yaml:

```
healthcheck:
  test: ["CMD-SHELL", "curl -F 'image=@/images/person.jpg' http://localhost:5000/v1/vision/detection || exit 1"]
  interval: 60s
  timeout: 1s
  retries: 1
```

Any thoughts?

Thanks!
