### ISSUE TITLE
Triggering the image_processing.scan service does not always update in home assistant

### ISSUE THREAD

**Issue by blackgold9** [robmarkcole/HASS-Deepstack-object#124]
Im running into the issue where triggering a scan does not always update the hass state, or save a new image to the specified folder. Sometimes it works, sometimes it doesn't, without any pattern i've been able to spot. 

I have deepstack object 3.1 configured talking to deepstack running on linux like so:
```
image_processing:
  - platform: deepstack_object
    ip_address: <IP Address>
    port: 5000
    api_key: !secret deepstack_key
    save_file_folder: /config/snapshots/
    # save_timestamped_file: True
    # roi_x_min: 0.35
    # roi_x_max: 0.8
    #roi_y_min: 0.4
    # roi_y_max: 0.8
    targets:
      - person
    source:
      - entity_id: camera.loft
```

I've noticed in the debug logs the webhook being called with data at the right timestamp, but then it appears to reference the timestamp of the old state in home assitant, and when i check the UI the state in the UI is still from the old timestamp in the log line.
