### ISSUE TITLE
can't guess the correct file_path of saved image

### ISSUE THREAD

**Issue by ebaschiera** [robmarkcole/HASS-Deepstack-object#125]
Hi,
thanks for this wonderful integration!
Could you please be more specific on the filename I should monitor if I specify a camera name?
Here's an example:
```
image_processing:
  - platform: deepstack_object
    ip_address: 192.168.0.140
    port: 8084
    api_key: !secret deepstack_object_api
    save_file_folder: /tmp/
    save_timestamped_file: True
    source:
      - entity_id: camera.frontdoor
        name: deepstack_frontdoor
camera:
  - platform: local_file
    file_path: /tmp/deepstack_frontdoor_latest.jpg
    name: deepstack_frontdoor
```

Is the value of file_path correct?
I can't get it to work, and IMHO documentation is lacking this kind of configuration. BTW detection works fine, so I believe it's just a matter of image path (in addition to the problem that I cannot browse the filesystem looking for the files).

Thanks!
