### ISSUE TITLE
Home Assistant State is "unknown" even if the user manually exectutes image_processing.scan

### ISSUE THREAD

**Issue by CarpeDiemRo** [robmarkcole/HASS-Deepstack-object#142]
**Environment**:
A. RPI4 HA installed IP.192.168.1.130
B. RPI4 DeepStack with NCS2 // Raspbian Buster IP.192.168.1.170

```
Active APIs:

/v1/vision/detection

---------------------------------------

v1/vision/addmodel

---------------------------------------

v1/vision/listmodels

---------------------------------------

v1/vision/deletemodel

---------------------------------------

v1/vision/setadminkey

---------------------------------------

v1/vision/setapikey

---------------------------------------

v1/vision/backup
```

**Addons**:
deepstack object custom integration &
deepstack face custom integration

configuration.yaml
```
  - platform: deepstack_object
    ip_address: 192.168.1.170
    port: 80
    api_key: xxxxxx-yyyyy-zzzzz-qqqq-oooooo
    save_file_folder: /config/www/deepstack/
    save_timestamped_file: True
    roi_x_min: 0.35
    roi_x_max: 0.8
    roi_y_min: 0.4
    roi_y_max: 0.8
    targets:
       - person
    source:
      - entity_id: camera.outside_ffmpeg
```

**How To**:
manually trigger
image_processing.scan
entity_id: image_processing.deepstack_object_outside_ffmpeg

Results:
1. In HA
![Screenshot 2020-08-10 at 20 17 27](https://user-images.githubusercontent.com/38489167/89810987-9f98b400-db46-11ea-96a3-9370418f9408.png)
2. In DeepStack Server
![Screenshot 2020-08-10 at 20 17 39](https://user-images.githubusercontent.com/38489167/89811019-ab847600-db46-11ea-818a-212df549dee0.png)

save_file_folder: /config/www/deepstack/ is emtpy

**Automation**

```
- alias: Image Motion ON Outside DeepStack
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.hikvision_outside_motion
  condition:
    - condition: state
      entity_id: binary_sensor.hikvision_bucatarie_motion
      state: 'on'
  action:
  - delay:
      seconds: 2
  - service: image_processing.scan
    entity_id: image_processing.deepstack_object_outside_ffmpeg
```
When the motion sensor is triggered a new entry is created on DeepStack server
`[GIN] 2020/08/10 - 17:58:29 | 200 |       70.48µs |   192.168.1.130 | POST     /v1/vision/detection`
HA status remains "unknown" 

**Attributes**

```
ROI person count: 0
ALL person count: 0
summary: 
{}

objects: 
unit_of_measurement: targets
friendly_name: deepstack_object_outside_ffmpeg
```
