### ISSUE TITLE
Automation not triggered after update to HA 0.115.2

### ISSUE THREAD

**Issue by koldogut** [robmarkcole/HASS-Deepstack-object#145]
Hi all, 
 
Event is detected and picture is boxed with the person detected, but automation is not triggered after upgrading to HA ver 0.115.2 

This is what the event listener outputs:

```
Evento 11 disparado 16:03:
{
    "event_type": "deepstack.object_detected",
    "data": {
        "bounding_box": {
            "height": 0.603,
            "width": 0.2,
            "y_min": 0.341,
            "x_min": 0.167,
            "y_max": 0.944,
            "x_max": 0.367
        },
        "box_area": 0.121,
        "centroid": {
            "x": 0.267,
            "y": 0.643
        },
        "name": "person",
        "confidence": 99.28,
        "entity_id": "image_processing.deepstack_object_pta_principal"
    },
    "origin": "LOCAL",
    "time_fired": "2020-09-21T14:03:05.789906+00:00",
    "context": {
        "id": "2bd0bb20fc1311ea9a9753a8e891fd74",
        "parent_id": null,
        "user_id": null
    }
}

```
and the configuration of the automation trigger:

```
event_data:
  object: person
event_type: deepstack.object_detected
platform: event
```

It's like the event data (object: person) doesn't match the event payload anymore. It was working fine untill last update  and automation works because other triggers (door sensors) make the automation start.

**Comment by speedst3r** [comment]
Could this possibly be related to https://github.com/home-assistant/core/pull/39884 ?

**Comment by koldogut** [comment]
Is the opposite, the automation in this case is not triggered.

**Comment by speedst3r** [comment]
I meant the change to trigger handling in HA core - there are examples in the HA forums of events not triggering automations

**Comment by robmarkcole** [comment]
Lets see if this is fixed in 0.116

**Comment by speedst3r** [comment]
I've got my triggers working in 0.115.2, I had to change the event_data to `name` instead of `object` and separate each object type into its own trigger:

```
  trigger:
  - event_data:
      name: person
    event_type: deepstack.object_detected
    platform: event
  - event_data:
      name: car
    event_type: deepstack.object_detected
    platform: event
  - event_data:
      name: motorcycle
    event_type: deepstack.object_detected
    platform: event
  - event_data:
      name: truck
    event_type: deepstack.object_detected
    platform: event
```
