### ISSUE TITLE
Custom models not calling correct _url_detect

### ISSUE THREAD

**Issue by radinsky** [robmarkcole/HASS-Deepstack-object#165]
Using v3.7,  is not working for custom model (it works correct for person detection on other cameras), here’s my ha config:
```
- platform: deepstack_object
    ip_address: 10.0.X.X
    port: 5000
    api_key: 30667XXXXXXXXXXXX
    custom_model: lock
    save_file_folder: /media/camera/bike_lock
    save_timestamped_file: True
    targets: 
      - locked
      - unlocked
    confidence: 85
    source:
      - entity_id: camera.bike_lock
        name: deepstack_bike_lock
```

Return: 
`2020-12-21 23:56:35 ERROR (SyncWorker_3) [custom_components.deepstack_object.image_processing] Deepstack error : Error from Deepstack request, status code: 400`

When testing the deepstack itself with:
`import requests
image_data = open("/XXXX/open_2207-16-53-30.jpg", "rb").read()
response = requests.post("http://10.0.XXXXXX:5000//v1/vision/custom/lock", files={"image": image_data}).json()`

```
>>response
{'success': True, 'predictions': [{'confidence': 0.95367974, 'label': 'unlocked', 'y_min': 0, 'x_min': 0, 'y_max': 250, 'x_max': 450}]}
```

Validated with deepstack-ui tool and deepstack itself and the model works ok (only not working within HomeAssistant):
![image](https://user-images.githubusercontent.com/4540268/103203831-811d3480-48fe-11eb-9f3e-a5fc204aab25.png)

![image](https://user-images.githubusercontent.com/4540268/103203843-8b3f3300-48fe-11eb-8e9f-7bd8ac22d02b.png)

**Comment by robmarkcole** [comment]
Hmm deepstack-ui is using the same dependency so I don't think there should be an issue. Note I believe you want:
```
 targets: 
- locked
- unlocked
```

Other than that are you able to share the model so I can try reproduce this?

**Comment by radinsky** [comment]
Sorry my bad, pasted my old config, I actually using:

```
  - platform: deepstack_object
    ip_address: 10.0.X.X
    port: 5000
    api_key: XXXX
    custom_model: lock
    # scan_interval: 30 # Optional, in seconds
    save_file_folder: /media/camera/bike_lock
    save_timestamped_file: True
    targets: 
      - locked
      - unlocked
    confidence: 75
    source:
      - entity_id: camera.bike_lock

```
updated the issue as well.
