### ISSUE TITLE
Document use of Media Browser

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-Deepstack-object#170]
We can use the built in Media browser to view images processed by Deepstack.

Example config:
```yaml

homeassistant:
.
.
  whitelist_external_dirs:
    - /config/images/
  media_dirs:
    local: /config/images/

media_source:

image_processing:
  - platform: deepstack_object
    ip_address: 192.168.1.84
    port: 80
    confidence: 50
    save_file_folder: /config/images/deepstack/foscam
    save_timestamped_file: True
    targets: car
    source:
      - entity_id: camera.foscam_camera
```

![image](https://user-images.githubusercontent.com/11855322/103435986-d020dd80-4c0e-11eb-8a4c-276083198432.png)
