### ISSUE TITLE
Invalid config for [image_processing.deepstack_object]: expected a dictionary @ data['targets'][0]

### ISSUE THREAD

**Issue by CarpeDiemRo** [robmarkcole/HASS-Deepstack-object#199]
```
Invalid config for [image_processing.deepstack_object]: value should be a string @ data['targets'][0]. Got OrderedDict([('target', 'person')])
value should be a string @ data['targets'][1]. Got OrderedDict([('target', 'vehicle'), ('confidence', 60)])
value should be a string @ data['targets'][2]. Got OrderedDict([('target', 'car'), ('confidence', 40)]). (See ?, line ?).
```

Everything works great until the last update.

configuration.yaml

```
  - platform: deepstack_object
    ip_address: localhost
    port: 80
    api_key: xxxxxx
    # custom_model: mask
    # confidence: 80
    save_file_folder: /config/www/deepstack/
    save_timestamped_file: True
    roi_x_min: 0.1 # optional, range 0-1, must be less than roi_x_max
    roi_x_max: 0.9 # optional, range 0-1, must be more than roi_x_min
    roi_y_min: 0.1 # optional, range 0-1, must be less than roi_y_max
    roi_y_max: 0.9 # optional, range 0-1, must be more than roi_y_min
    targets:
      - target: person
      - target: vehicle
        confidence: 60
      - target: car
        confidence: 40
    source:
      - entity_id: camera.xxxxxx
        name: DeepStack Person Backyard Detection 
```
Last good configuration

```
  - platform: deepstack_object
    ip_address: localhost
    port: 80
    api_key: xxxxxx
    save_file_folder: /config/www/deepstack/
    confidence: 50
    roi_x_min: 0.1 # optional, range 0-1, must be less than roi_x_max
    roi_x_max: 0.9 # optional, range 0-1, must be more than roi_x_min
    roi_y_min: 0.1 # optional, range 0-1, must be less than roi_y_max
    roi_y_max: 0.9 # optional, range 0-1, must be more than roi_y_min
    targets:
      - person
    source:
      - entity_id: camera.xxxxxx
        name: DeepStack Person Detection Outside
```
Now, with these settings, it detects everything, and object detection is not filtered anymore.

Did I miss something?

**Comment by robmarkcole** [comment]
As per the readme, targets are now configured differently:
```
    targets:
      - target: person
      - target: vehicle
        confidence: 60
      - target: car
        confidence: 40
```
