### ISSUE TITLE
Add cloud_backup option

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-Deepstack-object#202]
Currently we can save locally but add support for additionally saving to S3 (and other cloud locations in future?). Only requires a couple of lines from https://github.com/robmarkcole/HASS-S3 
Will greatly simplify the process for anyone who wants to store on locations as well as local, which currently requires automations using folder_watcher. 

Proposed addition to config:

```yaml
cloud_backup:
    - location: S3
      aws_access_key_id: AWS_ACCESS_KEY
      aws_secret_access_key: AWS_SECRET_KEY
      region_name: eu-west-1 # optional region, default is us-east-1
      bucket: foo
      key: bar
```
