### ISSUE TITLE
Installation instructions incomplete?

### ISSUE THREAD

**Issue by mjmare** [robmarkcole/HASS-Deepstack-object#207]
Hi, 
I'm having trouble getting HASS-Deepstack-object to work on HassIO (on Synology). 

I have installed Deepstack on Docker. I have verified that it works correctly and is accessible from the network(with a custom program). 

I have added:
```
image_processing:
  - platform: deepstack_object
    ip_address: 192.168.1.210
    port: 5000
    # api_key: mysecretkey
    # custom_model: mask
    confidence: 80
    save_file_folder: /www/snapshots/entree
    save_timestamped_file: True
    always_save_latest_jpg: True
    scale: 0.75
    # roi_x_min: 0.35
    # roi_x_max: 0.8
    #roi_y_min: 0.4
    # roi_y_max: 0.8
    targets:
      - target: person
      - target: vehicle
        confidence: 60
      - target: car
        confidence: 40
    source:
      - entity_id: camera.maxnas_entree_reolink_511
```
to my configuration.yaml.

When verifying the config I get this error: Platform error image_processing.deepstack_object - Integration 'deepstack_object' not found.

Per FAQ Q6  I have restarted the Synology NAS so Docker with Deepstack and HassIO has completely restarted.

Should other components be installed? There is no integration on: https://www.home-assistant.io/integrations/#search/deepstack

I am running HA 2021.1.5 (supervisor 2021.01.7).

Another thing: 
_whitelist_external_dirs_ is not a valid config parameter anymore. Probably replaced by_allowlist_external_dirs_
