### ISSUE TITLE
Feature proposal: Support object min/max size

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-Deepstack-object#209]
Allow config an object min/max size to allow filtering out incorrect detections which can clearly be differentiated by odd box size. Size will be specified as a % of the size of the total frame. 

Example config:
```yaml
- target: person
  min_size: 20 # %
  max_size: 40 # %
```

This will require adding a method to calculate the box size as % of the frame
