### ISSUE TITLE
config check never end if  platform: deepstack_object is enabled

### ISSUE THREAD

**Issue by anubisg1** [robmarkcole/HASS-Deepstack-object#231]
as per title, if i configure deepstack_object in home assistant image_processing , the "check config" process never ends and is impossible to restart HA from the UI.

the config i am using is this one

```
- platform: deepstack_object
  ip_address: 192.168.0.20
  port: 8090
  timeout: 10
  save_file_folder: /config/www/deepstack
  save_file_format: png
  always_save_latest_file: true
  targets:
    - target: person
      confidence: 70
  source:
    - entity_id: camera.czrsc_lan_cam01
```
