### ISSUE TITLE
Timestamped filename ends with _None 

### ISSUE THREAD

**Issue by sylarevan** [robmarkcole/HASS-Deepstack-object#243]
Hi there,

I would like, for debug burpose, to have access to each image that as been processed by deepstack.

Fortunately, the option `save_timestamped_file: True` is there for that purpose, but it does not seem to work, as the only file I get is something like : 
- `deepstack_object_synok_jardin_None.png`,
-  instead of, e.g., `deepstack_object_synok_jardin_2021-05-13_05-38-28.png`.  

Then, all images are saved with this `_None` name, and I do not have access to past processed pictures.

Any idea on the reason it is happening?

My deepstack custom component configuration:

```
image_processing:
  - platform: deepstack_object
    ip_address: 192.168.1.6
    port: 5000
    save_file_folder: /media/deepstack/
    save_file_format: png
    save_timestamped_file: True
    always_save_latest_file: True
    scale: 1.0
    show_boxes: True
    roi_x_min: 0
    roi_x_max: 1.0
    roi_y_min: 0.28
    roi_y_max: 1.0
    targets:
      - target: person
        confidence: 30
    source:
      - entity_id: camera.synok_jardin
```

I'm running v4.3.0 of deepstack object custom integration, and HA v.2021.5.4.

Thanks!
