### ISSUE TITLE
[Feature Request] Config "name" key pair for image processors 

### ISSUE THREAD

**Issue by Salvora** [robmarkcole/HASS-Deepstack-object#253]
Hello,
Is it possible to add "**_name_**" key to the config like below?
I use multiple detectors from different hosts using the same source camera so HA adds _2 to  the end of the entity which is not very helpful for identifying. A name key pair can help solve this problem.
Thanks in advance
```yaml
image_processing:
  - platform: deepstack_object
    name: Cam1_det
    ip_address: localhost
    port: 80
    api_key: mysecretkey
    # custom_model: mask
    # confidence: 80
    save_file_folder: /config/snapshots/
    save_file_format: png
    save_timestamped_file: True
    always_save_latest_file: True
    scale: 0.75
    # roi_x_min: 0.35
    roi_x_max: 0.8
    #roi_y_min: 0.4
    roi_y_max: 0.8
    targets:
      - target: person
      - target: vehicle
        confidence: 60
      - target: car
        confidence: 40
    source:
      - entity_id: camera.local_file
```
