### ISSUE TITLE
Component looks to be writing to two locations

### ISSUE THREAD

**Issue by robbrad** [robmarkcole/HASS-Deepstack-object#257]
Hi Rob

Sorry if this is a non issue but im having a hard time working out why there are two copies saved via the component.

In my image processing config I have:

```
- platform: deepstack_object
  ip_address: localhost
  port: 5000
  save_file_folder: /Fileserver/deepstacksnapshots/
  save_timestamped_file: true
  show_boxes: true
  targets:
    - target: person
  source:
    - entity_id: camera.RSC
```

Files get saved fine - however I noticed that files are also written to /ha-config/www/person_detected

Do you know why this is ?

My automation works like this

Camera Emails image and motion alert
To an email to MQTT container which saves the image and sets off a binary sensor 
Camera Motion Binary Sensor Triggers a save snapshot to /ha-config/www/camera_snapshot/frontdoor_latest.jpg
Action is a deepstack scan - with the above config
