### ISSUE TITLE
Platform error image_processing.deepstack_object - No module named 'deepstack'

### ISSUE THREAD

**Issue by MTrab** [robmarkcole/HASS-Deepstack-object#81]
Seeing this error, which prevents restart of Home Assistant:
`Platform error image_processing.deepstack_object - No module named 'deepstack'`

This is the YAML used for define:

```
image_processing:
  - platform: deepstack_object
    ip_address: localhost
    port: 5000
    api_key: !secret deepstack_api_key
    save_file_folder: /config/www/deepstack_person_images
    target: car
    source:
      - entity_id: camera.driveway
        name: person_detector
```

I'm using version `v2.1` of `Deepstack Object Custom Component`, installed from HACS, installed on Home Assistant `v0.100.2`.
