### ISSUE TITLE
Can bounding boxes for objects be returned?

### ISSUE THREAD

**Issue by i00** [robmarkcole/HASS-Deepstack-object#97]
Currently objects get a count returned when doing a "scan" like this:
```yaml
summary:
  cup: 1
  bowl: 1
  couch: 1
unit_of_measurement: people
friendly_name: Living Room
icon: 'mdi:human-handsdown'
```
Can you make it so it returns the bounding boxes for the "cup(s)" etc ... rather than just 1...

Also it would be nice to also have a "camera" that shows bounding boxes for everything ... with text in the bottom right of each box telling you the object.
