### ISSUE TITLE
local file latest person not created

### ISSUE THREAD

**Issue by Misak** [robmarkcole/HASS-Deepstack-object#99]
Hello, sorry for creating issue, but I can't make it work. Curl with image to docker is working fine. From homeassistant, I have deepstack_object custom component installed, but image_processing.deepstack_person_detector is not showing anything and camera from local_file is empty (/config/www/deepstack_object_local_file_latest_person.jpg is not created). And I don't see any errors in logs.

here is my setup:

```
homeassistant:
  whitelist_external_dirs:
    - /config/www/

image_processing:
  - platform: deepstack_object
    ip_address: 10.1.1.10
    port: 5000
    api_key: Mysecretkey
    # scan_interval: 30 # Optional, in seconds
    save_file_folder: /config/www/
    save_timestamped_file: True
    source:
      - entity_id: camera.generic_camera
        name: deepstack_person_detector

camera:
  - platform: local_file
    file_path: /config/www/deepstack_object_local_file_latest_person.jpg
    name: deepstack_latest_person

```
Any suggestion would be appreciated.
